### ISSUE TITLE
20150201 스터디 장소 예약

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#1]
<h1> 스터디 장소를 예약합니다. </h1>
<h3>반드시 필요한 요건은 다음과 같습니다.</h3>
* 14명 이상이 앉을 수 있을 것 
* 강남역 일요일 3시까지 가기 쉬울 것
* 프로젝터가 있을 것

<h3>고려중인 장소</h3>
* TOZ 강남 2호점
* 공간스페이스 공간13번방
* ENI 스터디 모임

<h3>TOZ 강남 2호점</h3>
* 공간 사용료 2시간 : 12만원 + 프로젝터 사용료 2시간 : 1만원
* 시설이 가장 좋고 분위기도 좋음 (우리가 처음 만났던 방입니다)
* [http://www.toz.co.kr/booth/main/list.htm?cd1=3&cd2=11&id=84]
* MS 지원으로 여러 지원을 받는 만큼 활용하는 것이 편함
* 할인을 위해서는 기업회원이 필요하다고 함 (10% 할인)

<h3>공간스페이스</h3>
* 공간 13의 경우 2시간 8만원(?) + 6천원(프로젝터) 비용
* TOZ 에 비교하여 공간이 협소함, 대신 TOZ 예약이 불가능할 경우 대비할 만함
![screen shot 2015-01-25 at 7 10 56 pm](https://cloud.githubusercontent.com/assets/979297/5891128/1b4ac682-a4c6-11e4-942e-1ade344cc47b.png)

**Comment by makecake** [comment]
지난 번에 토즈에서 해봤으니 이번에는 다른 곳에서 해보고 장단점을 봐서 이후 일정을 정해도 되지 않을까 싶습니다. 자주 돌아다니는 저는 약간 덜 민감한데 이건 개인차가 있는 부분이긴 할 것 같습니다 :)

**Comment by iz4blue** [comment]
이번에는 공간스페이스에서 하기로 저 혼자 결정 내렸습니다...
우선 가격도 저렴하고 위치도 11번 출구랑 1분 거리고 방도 좋습니다
예약 금액이 환불이 안되고 30% 가 좀 쎄긴해도 훨씬 좋은 것 같습니다
자세한 것은 곧 공지하도록 하겠습니다

**Comment by iz4blue** [comment]
이번에는 공간스페이스에서 하기로 저 혼자 결정 내렸습니다...
우선 가격도 저렴하고 위치도 11번 출구랑 1분 거리고 방도 좋습니다
예약 금액이 환불이 안되고 30% 가 좀 쎄긴해도 훨씬 좋은 것 같습니다
자세한 것은 곧 공지하도록 하겠습니다

**Comment by zipel2** [comment]
@iz4blue  공간더하기 가격은 어떻게 되나요??
