### ISSUE TITLE
윈도우에서 p.48 예제 실습

### ISSUE THREAD

**Issue by zipel2** [iz4blue/study_jQuery_HeadFirst#10]
```
<script src="scripts/jquery-1.11.2.min.js"></script>
```

윈도우에서 scripts란 폴더를 만들고 위와 같이 소스코드를 작성했는데, JQuery를 못 불러 오네요.
어떻게 설정해야 할까요?

Scripts 폴더의 경로가 C:\Users\재관\Desktop\scripts 인데
```
<script src="C:\Users\재관\Desktop\scripts\jquery-1.11.2.min.js"></script>
```
혹은
```
<script src="C:/Users/재관/Desktop/scripts/jquery-1.11.2.min.js"></script>
```
로 해도 작동이 되지 않아요 ㅠㅠ

**Comment by makecake** [comment]
index.html 안에 scripts 폴더가 있으면 될 듯 싶긴해요.

@iz4blue 파일저장위치 내일 정리하자고한게 이 부분이 다른 경우에도 자주 질문 나오더라구요. 내일 함께 정리한 번 해야할 듯.
2015. 1. 31. 오후 1:36에 "Linux Class" <notifications@github.com>님이 작성:

**Comment by iz4blue** [comment]
@zipel2 @makecake 음 브라우져에서 접근하는 파일 경로는 file:// 이라는 프로토콜로 사용됩니다.
그리고 말씀하신 것과 같이 상대 경로와 절대 경로에 관련된 부분을 이야기 해야겠네요.

@zipel2 폴더 경로를 사진으로 찍어서 올려주시면 제안이 가능할 것 같아요.

**Comment by makecake** [comment]
저도 윈도만 쓰다 이번부터 맥으로 해보려 하는데 맥에서 경로는 어떤지 부탁드려요.
2015. 1. 31. 오후 1:58에 "김정환" <notifications@github.com>님이 작성:

**Comment by iz4blue** [comment]
@makecake 상대 경로로 하시는 것이 좋을 것 같습니다.
```
<script src="scripts/jquery-1.11.2.min.js"></script>
```
와 같이 하위에 하나 폴더를 만드시거나 상위에 scripts 폴더가 있다면
```
<script src="../scripts/jquery-1.11.2.min.js"></script>
```

**Comment by zipel2** [comment]
![-](https://cloud.githubusercontent.com/assets/3910437/5988046/462dca46-a991-11e4-9b63-06b6fb6774a5.jpg)

경로는 이렇게 됩니다!

**Comment by iz4blue** [comment]
@zipel2 노트북을 통째로? 가져와 주세요. ㅋ

**Comment by iz4blue** [comment]
#5 여기서 나왔던 끝에 .js 가 이미 붙어 있어서 파일명을 알아보기 어려운 경우였습니다.
