### ISSUE TITLE
jQuery 다운을 어떻게 받아야 할지 모르겠어요.

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#13]
http://jquery.com/download/

파일들이 여러게 있어요. 그리고 책이랑 버젼이 달라요.

![screen shot 2015-02-01 at 4 01 00 pm](https://cloud.githubusercontent.com/assets/979297/5991343/8df11550-aa2b-11e4-8b78-79c7dd6b175e.png)

**Comment by iz4blue** [comment]
@hotzzi 이 화면을 보시는게 맞나요?

**Comment by hotzzi** [comment]
맞아용

=====================
윤하지 Ha-ji.YOON
UX Designer

Email : YOON.haji@andbut.com  |  Mobile : 010-3292-8585

*㈜앤벗 / AndbuT Inc.*
서울특별시 성동구 왕십리로 222 한양대학교내 연구동 902호 (우)133-791
#902 Research Center, 222, Wangsimni-ro, Seongdong-gu, Seoul, 133-791 Rep.
of KOREA

회사 홈페이지: http://andbut.com/  <http://andbut.com>
서비스 홈페이지: http://userhabit.io/

2015년 2월 1일 오후 4:01, 김정환 <notifications@github.com>님이 작성:

**Comment by iz4blue** [comment]
해결이 됐어요.
