### ISSUE TITLE
한글이 깨져요 도와주세요.

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#14]
한글이 깨져서 계속 encoding 을 수정하고 있습니다.
혹시 이것이 불편해서 그런데 편하게 볼 수 있는 방법은 없을까요?

**Comment by iz4blue** [comment]
``` <head> ``` 엘리먼트 안에 다음의 코드를 넣어주세요.
``` <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> ```

**Comment by iz4blue** [comment]
@zenerify 응? 그 내용으로 안되시는 건가요? 대충의 소스 코드를 올려주세요~

**Comment by zenerify** [comment]
윈도우의 경우 에디트 플러스에서 썼을땐 UTF-8을 쓰기 위해서 별도 설정을 했던 기억이 있는데요 
서브라임에서도 설정이 필요한 건지 코드만 바로 썼을 경우 한글 깨짐 현상이 해결되지 않습니다. 
```
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR" />
```
임시로 끝에 EUC-KR을 적어 쓰고 있는데 혹시 별도 설정이 필요한가요?

**Comment by iz4blue** [comment]
@zenerify 아 윈도우... 윈도우에서 서브라임이 UTF-8 로 시작하도록 설정하는걸 찾아봐야겠네요.
mac 은 기본 UTF-8 로 시작하니 제가 고려를 못했네요.

**Comment by iz4blue** [comment]
만약에 메타 테그를 붙이고도 문제가 생기면 save with encoding 으로 UTF-8 을 지정해서 다시 해보세요.

**Comment by zenerify** [comment]
@iz4blue 감사합니다 :+1:  알려주신 방법으로 해결했어요!
