### ISSUE TITLE
DOM과 jQuery에 대한 내용

### ISSUE THREAD

**Issue by makecake** [iz4blue/study_jQuery_HeadFirst#15]
오늘 스터디 때 이야기한 내용인데 DOM과 jQuery를 함께 설명한 블로그 글을 공유합니다.

jQuery와 DOM 첫걸음 http://www.nextree.co.kr/p9747/

CSS 선택자에 대한 포스팅도 있네요. http://www.nextree.co.kr/p8468/

**Comment by iz4blue** [comment]
2장에 좀더 적합한 이야기 같아서 2장으로 변경했습니다. ^^

**Comment by kskyung4u** [comment]
좋은 정보 공유 감사합니다~
css 선택자도 제대로 골라내려면 장난 아니네요ㅋ
근데 css lv3 수준은 그냥 id,class로 선언하고 불러드리는게 훨씬 편할꺼 같은데
왜 저런 수고를 하는 걸까요?ㅇ.ㅇ

**Comment by iz4blue** [comment]
@kskyung4u 모든 데이터가 다 속성요소를 지니게 되면 html 소스가 무거워지는 이유도 생기겠죠.
또한 모든 데이터는 우리가 원하는 형태가 아닌 경우가 많습니다.
