### ISSUE TITLE
2/8 스터디 장소 예약

### ISSUE THREAD

**Issue by makecake** [iz4blue/study_jQuery_HeadFirst#19]
아래 내용과 같이 일요일자 예약해두었습니다. 만약에라도 금전적인 어려움을 느끼실까봐 2월의 절반은 적절히 해결할 예정이니 스터디 전에 예습 잘하고 오세요. 그럼 주말에 뵙겠습니다 ^^
 
일시 2015년 2월 8일(일) 15:00 ~ 17:00
장소 TOZ모임센터 강남점 / 최소 15인부스
서울시 서초구 서초대로77길 23 (서초동 1307-26 승원빌딩 3~4층)
http://www.toz.co.kr/branch/main/index.htm?id=10
모임명 LEED 모임 / 배성환
시스템 빔프로젝트
좌석 세팅 강의형식(15석)

**Comment by hyejin-lee** [comment]
전에 사전모임때 했던  TOZ모임센터 동일한데 맞나요?

2015년 2월 3일 오후 6:43, makecake <notifications@github.com>님이 작성:

**Comment by makecake** [comment]
@hyejin-lee 강남점은 지하철역 2호선에서 더 가까운 곳입니다.
강남점 : 서울시 서초구 서초대로77길 23 (서초동 1307-26 승원빌딩 3~4층) http://www.toz.co.kr/branch/main/index.htm?id=10

**Comment by makecake** [comment]
@iz4blue 22일은 연휴라 못할테고 저희 15일에 스터디 진행인가요? 멜팅팟과 연락 때문에 확인 부탁합니다.

**Comment by iz4blue** [comment]
15일은 합니다. 제가 일이 갑자기 몰리니 -_-; 여러가지를 신경 못 쓰고 있습니다.
그 상황에서 챙겨주시는 성환님께 매우매우 감사드리고 있습니다.

15일 3장 진행합니다!

**Comment by hotzzi** [comment]
@iz4blue 3장까지 읽어와야하나요?

**Comment by iz4blue** [comment]
2장까지는 순조롭게 나가셨나보네요?
3장까지 간다는 이야기는 없어서 3장을 안하셔도 되기는 하는데...

3장 읽으신 분이 많다면 진도를 조금 빨리 빼야 겠네요 ㅋ

**Comment by hotzzi** [comment]
@iz4blue 아아 15일이 다음주였군요; 주말에 급 약속이 생겨서 스터디를 못 갈 것 같아요. ㅠㅠ 혹시 강의슬라이드 공유 가능할까요?

**Comment by iz4blue** [comment]
@hotzzi 저는 강의 자료만 봐서는 이해가 안가는 자료를 만들어서요 -_-;;;
그리고 강의 자료보다는 질문을 올려주시는게 도움이 될꺼 같아요. 자료는 공유해드릴께요.

**Comment by makecake** [comment]
커뮤니티에 올라온 다음 링크 내용 중에도 jQuery나 js로 활용하는 부분은 이번 주 아니더라도 같이 보면 좋겠네요.
http://www.fbml.co.kr/2014/08/14/14-tools-data-visualization/
2015. 2. 8. 오전 9:40에 "김정환" <notifications@github.com>님이 작성:
