### ISSUE TITLE
sublime 간단 사용법 적기

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#2]
Wiki 에 sublime 간단 사용법 적어나가기

**Comment by iz4blue** [comment]
[https://github.com/iz4blue/study_jQuery_HeadFirst/wiki/Sublime#sublime-설치하기-및-기본-사용법]
위 주소로 계속 업데이트 하면 될 듯 싶네요.
어플리케이션 설치하고 저장하고 수정하고 하는 것들 자체는 쉬운 것 같으니...
탭말고 스페이스 4개로 통일한다거나 하는 것만 맞추면 될듯 싶네요.

**Comment by makecake** [comment]
지난 모임에서 비용에 관한 부분 이야기 드렸는데 찾아보니 이 부분이 기억나서 얘기드렸던 것 같아요.
유료인듯 유료아닌 유료같은...
"Sublime Text 2 may be downloaded and evaluated for free, however a license must be purchased for continued use. There is currently no enforced time limit for the evaluation."

**Comment by iz4blue** [comment]
@makecake 한동안은 팝업창이 떠서 귀찮게 안한다고 하더라구요.
하지만 한동안이 지나면 팝업창이 떠서 귀찮게 한다는 이야기가 있더라구요.

**Comment by makecake** [comment]
누가 이걸 추천해줘서 오늘 사용해봤습니다. 디자이너에 최적화되어 있는 에디터라고는 하는데 오픈 소스인 듯 싶고 반응이 약간 느린 거랑 html/css/js 지원 형태입니다. 우리 스터디에는 괜찮을 수도 있겠어요. psd와 연계성이 있다고 합니다. 자세한 건 다음 사이트 참조. http://brackets.io/
@iz4blue Brackets는 어떻게 생각하세요? 그래도 Sublime Text 2? 다른 분들도 의견 부탁요.

**Comment by hyejin-lee** [comment]
Brackets 사용후기 보니까 꽤 쓸만한것 같아보이는게 한번쯤 이용해봐도 좋을듯 싶네요^^ 
사용후기 참조 https://justhackem.wordpress.com/2013/12/14/brackets/

**Comment by zipel2** [comment]
@makecake 브라켓, 서브라임 텍스트 모두 써봤는데 괜찮아요! 브라켓은 처음 쓰시거나 디자이너 베이스인 분들에게 괜찮은 것 같고 서브라임 텍스트는 개발자의 답답한 개발 환경을 쬐금?? 알고 싶다면! 
스터디원분들 의견에 따라서...

**Comment by iz4blue** [comment]
@makecake @hyejin-lee @zipel2 말씀하신 것 모두 일리가 있네요.
우선은 초반에 따라오실 분들을 위해서 일단 sublime 으로 가고 3~4장 이후에 제가 먼저 좀 파악해보고 이걸 써보는 것도 좋겠네요.
초반에 에디터를 굳이 통일하려고 했던 것은 구문 강조 기능 때문이였습니다.

이 툴이 좋은건 실시간성과, 연관 CSS 속성을 보여주는 것 (별도에 파일에 있다고 해도), 그리고 디버깅 기능인데 들인데...
이걸 모두 잘 다루려면 아무래도 시간이 좀 있어야 할 것 같네요.
4장쯤 나가게 되면 디버깅 이슈 이야기가 나올 것 같으니 그 때 시작해도 괜찮을 것 같습니다.
