### ISSUE TITLE
p.87 퀴즈의 3번 문항 이해가 안가요

### ISSUE THREAD

**Issue by hotzzi** [iz4blue/study_jQuery_HeadFirst#21]
> 어느 브라우저에서나 동작하는 자바스크립트 메서드로 요소를 식별할 수 있습니다. 

클래스는 안되고 ID만 되는게 정답인데, 어떤 의미인지 잘 이해가 안되네요?
```
$(.nav).click ();
```
이런 식으로는 안된다는 말인가용?

**Comment by iz4blue** [comment]
@hotzzi 아마도 제 생각에는 번역이 조금 아쉽게 된 듯 싶네요.
'어느 브라우저에서나 동작하는 자바스크립트 메서드로 요소를 식별할 수 있습니다.'
'어느 브라우저에서나 동작하는 자바스크립트 메서드로 지정한 요소를 식별할 수 있습니다.' 가 맞지 않을까? 싶네요.

```$(.nav).click ();``` 와 같은 것은 클래스 지정법이구요. ```$(#id).click();``` 와 같은 id 지정법이 답일 듯 싶습니다.

그리고 jQuery 가 아닌 자바스크립트로 ID를 식별하려면 다음과 같습니다.
``` document.getElementById("xyz"); ```
