### ISSUE TITLE
내일 공지 전에 같이 하는 분들께 먼저 질문

### ISSUE THREAD

**Issue by makecake** [iz4blue/study_jQuery_HeadFirst#25]
학교나 단체에서의 강의자이거나 또는 회사 교육 업무를 전체든 일부든 담당하고 계신 분이 우리 내부에도 있나요? 만약에 있으시면 알려주세요. 제가 외부 공지 준비하다가 먼저 따로 문의 드려서 확인해봐야겠다 싶은 내용이 있어서요. 내일 오전까지만 알려주시면 됩니다 :) 이후 삭제 예정ㅎ

**Comment by iz4blue** [comment]
@makecake github 에서는 이슈 삭제가 안되는 것 같더라구요.
그냥 이슈의 내용을 지우셔야 할 꺼에요.

**Comment by makecake** [comment]
ㅇㅇ 그러게요. 그래서 딱히 본문내용을 자세히 적진 않았어요.
