### ISSUE TITLE
Github 에 Issue 올리고 보는 법 익히기

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#3]
Github 에 Issue 를 올리고 보는 법을 익혀서 질문/답변 받는 것에 익숙해진다.

<h2>github 가입 이후 이곳을 watch 해둬야 질문 답변을 받을 수 있습니다.</h2>
watch 하신분은 이곳에 자신의 성함과 같이 코멘트를 남겨주세요.<br>

**Comment by hyejin-lee** [comment]
이혜진 :+1:

**Comment by iz4blue** [comment]
아참 저는 김정환입니다. ^^

**Comment by makecake** [comment]
[배성환] [www.facebook.com/cake.strategy] [화이팅!]

**Comment by zenerify** [comment]
이고은입니다! :blush:

**Comment by kskyung4u** [comment]
경건수입니다~!

**Comment by iz4blue** [comment]
@zipel2 님과 @hotzzi  님도 소개 부탁드려요 ^^

**Comment by hotzzi** [comment]
윤하지입니다 :dancer:

**Comment by chloeleejh** [comment]
재희에요. 모바일 깃허브는 하위 페이지가 안뜨네요 저만 그런지..?

**Comment by iz4blue** [comment]
@chloeleejh 사진을 캡춰해서 올려주면 이해가 더 편할 것 같아요. 무슨 말인지 이해를 못했어요.

**Comment by chloeleejh** [comment]
@iz4blue 이젠 돼요 어젠 모바일 앱에서 이슈 누르면 계속 아무것도 안떴어서 ㅎㅎ

**Comment by iz4blue** [comment]
@seungmiyo 소개 부탁드려요 ^^

**Comment by iz4blue** [comment]
아 그리고 여러분 아시는지 모르겠지만 메일이 온 것에 답장을 달면 바로 이곳에 달려요.
즉 등록된 이슈에 대해서 메일이 오면 그냥 답장을 하셔도 편하게 질문/답변을 할 수 있다는 것이죠.
한번씩들 해보시면 재미있을꺼에요 ^^

**Comment by seungmiyo** [comment]
소개가 늦었습니다 ㅠ 이승미입니다! 깃허브 어렵네요ㅠ

**Comment by iz4blue** [comment]
@zipel2 님의 자기 소개가 없군요 ㅋ
