### ISSUE TITLE
할인코드를 1부터 10사이가 아니라...지문에서 질문입니다(151p)

### ISSUE THREAD

**Issue by kskyung4u** [iz4blue/study_jQuery_HeadFirst#30]
151p
에밀리가 할인코드를 1부터 10사이가 아니라 100까지로 해달라고 하는데
150p
할인코드 난수의 범위는
```
funtion getRandom(5){
  var my_num = Math.floor(Math.random()*5);
  return my_num;
}
```
이므로 0-4까지의 할인코드 값 밖에 나올 수 없는 것 같은데
왜 에밀리는 할인코드를 1부터 4사이가 아니라 100까지를 요청한게 아니라
1부터 10사이라고 하는거죠? 너무 소심하게 따지고 드는건가;;;ㅎ

**Comment by iz4blue** [comment]
한 15분 정도 책을 뒤져 봤는데, 저자도 흐름 자체에 대해서는 버그(?)를 낸 것이 맞는 것 같네요.

* 처음 요청 5~10% 할인율 요청
* 코드를 수정하다가 최소 % 를 고려하지 않는 식으로 수정
* 에밀리도 5~10%가 아니라 1~10% 였다고 이해
* 그 뒤 100 까지로 코드가 변경

그 시간에 우리는 함수 자체의 코드만 가지고 이야기 했습니다.
질문 자체도 함수의 흐름만을 가지고 물어보셨구요.

지금 질문 하신 것과 같이 getRandom 은 0~4 까지가 나오는 것이 맞습니다.
올림 : Math.ceil(); 버림 : Math.floor(); 반올림 : Math.round(); 이니깐요.

가만히 기억을 해보면 ``` var my_num = Math.floor((Math.random() * 5) + 5);``` 코드에서
5~10 이 나올 수 있는 것이 아니라 5~9 까지밖에 나올수 없는 것이 아니냐? 하셨던 걸로 기억합니다.

그 시간에 제가 답하길 5~10 까지 나올 수 있다고 한거 같은데 floor 함수 특성상 버림을 하니깐 5~9까지 나올 수 있는 것이 맞습니다.
저도 정확하게 확인하지 않고 답을 한 것 입니다.
근데 우리가 아는 5% ~ 10% 가 초과, 미만 인지? 아니면 포함 인지와 영어에서는 between 일 때라고 가정해보면 그 녀석 역시 초과, 미만인지도 궁금하네요.

아무튼 제가 수업시간에 이야기 했던 건 floor 함수를 확인하지 않고 답변헤서 잘못된 답을 드렸고,
질문하신 것과 같이 책의 흐름이 조금 이상한 부분은 있는 것 같습니다.
