### ISSUE TITLE
jQuery 다운 받는 법이 책이랑 달라요

### ISSUE THREAD

**Issue by iz4blue** [iz4blue/study_jQuery_HeadFirst#5]
책이랑 jQuery 다운 받는 법이 달라서 고민이에요.
책에서는 jQuery-1.6.2.min.js 이걸 받으라고 하는데 어떠게 해야할지 모르겠어요.

@hotzzi 님 이렇게 질문하시면 되요. 다른 분들도 분명히 겪으실텐데 다른 버젼을 받고 계시려나요?

**Comment by iz4blue** [comment]
http://jquery.com/download/ 이 주소에서 1.11.2 버젼을 받으시면 되겠네요.
굳이 1.6.2 버젼으로 받으실 필요는 없습니다.

**Comment by hotzzi** [comment]
아, 질문이 있으면 이슈등록을 하면 되는군요? 감사합니다~

**Comment by iz4blue** [comment]
이 부분을 해결하기 위해서 겪었던 몇가지 상황을 적어둡니다.

* 확장자가 가려져서 혼란이 있는 부분 (브라우져의 문제)
* Safari 에서는 오른쪽 클릭으로 다름이름으로 저장할 때 webarchive 이라는게 따라 붙는 증상
* 책과 버젼이 달라서 사람들이 혼동이 있는 문제
* 상대경로 절대 경로를 어떻게 할지 몰라 혼선이 있는 문제
