### ISSUE TITLE
p.48 예제 실습 

### ISSUE THREAD

**Issue by hotzzi** [iz4blue/study_jQuery_HeadFirst#6]
그대로 따라 적었는데,
```
<script src="scripts/jquery-1.6.2.min.js"></script>
```
부분을 
```
<script src="scripts/jquery-1.11.2.min.js"></script>
```
이렇게 바꿨거든요? 왜 적용이 안될까용

**Comment by iz4blue** [comment]
@hotzzi 이미지가 없어요 아하하하 +_+a

**Comment by iz4blue** [comment]
@hotzzi 아 소스코드를 그대로 쓰셨군요. 지금 수정을 하다가 확인했는데...
소스 코드는 다음과 같은 문자 안에 쓰셔야 합니다.
![screen shot 2015-01-29 at 12 04 11 am](https://cloud.githubusercontent.com/assets/979297/5939846/6bfcf542-a74a-11e4-9e13-93cd4b730d3e.png)

**Comment by iz4blue** [comment]
@hotzzi jquery 를 저장하셨을때의 위치와 이름을 어떻게 하셨는지 모르겠네요.
혹시 맥이셨으면 저장하실때 다음과 같이 확장자명을 유념하셔야 합니다.
![screen shot 2015-01-29 at 12 19 36 am](https://cloud.githubusercontent.com/assets/979297/5940192/90161628-a74c-11e4-8bd7-8b94d6d2fcba.png)

**Comment by makecake** [comment]
폴더위치가 다를 수 있습니다.

**Comment by makecake** [comment]
폴더위치가 다를 수 있습니다. 우선은 index.html에 scripts 폴더가 있는지 확인하세요. (scripts 폴더 안에 jquery가 있어야 합니다.)
