### ISSUE TITLE
1장 리뷰 키워드 정리

### ISSUE THREAD

**Issue by makecake** [iz4blue/study_jQuery_HeadFirst#8]
1장에선 다음 내용에 대해 다루면 어떨까요.

DOM
마크업
CSS 리뷰(선택자 중심으로)
img, src 등을 위한 위치 지정 방법(/사용 기준, 일반적인 저장 위치)
jQuery 기본 문장

**Comment by iz4blue** [comment]
@makecake 좋은 포인트네요. 우선은 1장을 이해하느냐와 1장에서 나온 내용에 대해서 좀더 보충을 하느냐가 정해지고 나면 다시 말씀드리겠습니다.
(아니면 나중에 이런 키워드들을 따로 모아서 보충설명 시간을 가져도 ^^)
우선 급한데로(?) 읽으시면 참조가 될만한 URL 들을 모아봅니다.

DOM : Document Object Model : [http://wiki.gurubee.net/pages/viewpage.action?pageId=6259958]
Markup Language : [http://cnc1gi.com.ne.kr/htm/htm10.htm]
CSS selector : [http://www.nextree.co.kr/p8468/]
CSS basic : [http://www.clearboth.org/css3_1_by_isdn386/]

jQuery 기본 문장은 어떤걸 이야기 하신지 잘 모르겠어요. 앞으로 계속 배워나갈텐데 간단한 활용을 말씀하시는 건지?

**Comment by makecake** [comment]
@iz4blue 개인적으론 1장은 쉽게 지나갔는데 모든 사람들이 정리하기엔 위 내용들이 필요할 것 같아서 정리했습니다. 실제로 1장에는 그 이상의 내용은 없긴하죠ㅎ

마지막의 jQuery 기본 문장은 말그대로 가장 기본 형태의 문법에 대한 설명이요. (책에 나온 그대로를 함께 봐도 충분할 듯)

1장이 제대로 정리되려면 마크업 - HTML과 CSS의 완전 기본 문법 - CSS의 선택자 - DOM - jQuery 기본 문법 - 기타 Tip (jQuery 설치, 코딩 중 특정 파일의 위치지정 방법 등)의 순서대로가 어떨까 생각됩니다.
2장부터는 책 의존도가 점점 더 높아지긴 하겠네요.

**Comment by iz4blue** [comment]
@makecake 아무래도 다음에 1장만 이야기 하는건 시간이 남겠죠?
2장도 준비하고 싶은데 대부분 토요일날 많이들 보시려나요? 음...

**Comment by makecake** [comment]
다른 분들이 어떠실지 정확히 모르겠지만 1장의 경우 위에 말씀드린 리뷰 요소를 하나에 15분 정도 배정해도 75분이면 되니까 2장도
어느 정도 보실 수 있지 않을까 싶긴합니다. (물론 HTML과 CSS 리뷰하는 부분에 얼마나 시간을 주었느냐에 달린 것 같긴 합니다.)

1장만 봤다면 선택자는 결국 알고는 있는 거니까 가능한 부분까진 예습하듯 하면 어떨까도 싶어요. 아니면 2장 어디까지라고 정해주셔도
좋을 것 같네요.

2015년 1월 29일 오후 1:53, 김정환 <notifications@github.com>님이 작성:
