### ISSUE TITLE
1장을 마쳤습니다...근데

### ISSUE THREAD

**Issue by kskyung4u** [iz4blue/study_jQuery_HeadFirst#9]
1장은 개념적인 내용도 많고 분량 자체가 그리 많지 않아서 술렁술렁 책내용 한 번 훝어보고, 코딩하고 그러면서 마무리 하였습니다.

근데...연습문제를 풀다가 궁금증 또는 문제가 하나 생겼습니다. 연습문제나 실전문제를 풀다가 막히는 부분이 생기면 어느정도 고민을 하고 답을 못 찾았을 때 답을 확인하는게 좋을까요?

저는 사고를 하다가 막히면 졸음이 오는 스타일이라 5분정도 고민하고 안나오면 바로 답을 찾아보는데 너무 쉽게 찾아서 해결능력이 떨어질꺼 같기도 하고 어렵네요

학생 때, 문제집 풀 때 항상 고민했던 내용인데...프로그래밍 공부하다가 또 이 문제에 직면하네요
다른 분들은 어떠신지 궁금하고 좋은 해답있으면 공유 부탁드려요~

p.s. 저는 2장까지 보고 스터디 갈 생각인데..그래도 수업은 1장 위주로 진행하는게 맞다고 생각해요~ 일단 정식 공지한 사항이고 공지에 따라 학습해왔는데 손해(?)를 보게되믄 1장까지 해오신 분들이 억울하실 수도 있을꺼 같습니다. 아래 분이 올려주신 1장의 키워드를 좀 더 심도있게 보더라도 아예 2장까지는 안나갔으면 좋겠습니다.

**Comment by iz4blue** [comment]
책보고 연습하는 것이야 뭐 답이 있으니깐 사고 능력 떨어진다 이런 느낌을 받으시겠지만...
디버깅이라는 것이 생각해보면 엄청 자주 시도해보는 방법 뿐이더라구요. (주변에서 잘하는 친구들 보면)
그런 생각해보면 큰 구조를 짜는 연습을 자주 하시고, 실제 코딩은 디버깅을 빨리 빨리 하면서 키보드 한자라도 더 치면서 코드를 고치는 연습을 하시는게 맞는 것 같습니다.

저 역시 사고를 하다가 막히면 졸려하는 스타일이라 ... 지금까지도 큰 발전이 없네요 -_-
